-- MySQL Script generated by MySQL Workbench
-- Mon Mar 19 22:41:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Video Subject and Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Video Subject and Tag` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Video Subject and Tag` (
  `Vid_ID` VARCHAR(45) GENERATED ALWAYS AS () VIRTUAL,
  `Action_Object` VARCHAR(45) NULL,
  `Tag_ID` VARCHAR(45) NULL,
  PRIMARY KEY (`Vid_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Frame Rerence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Frame Rerence` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Frame Rerence` (
  `Vid_ID` VARCHAR(45) GENERATED ALWAYS AS () VIRTUAL,
  `Frame_CL` VARCHAR(45) NULL,
  PRIMARY KEY (`Vid_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Video Resolution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Video Resolution` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Video Resolution` (
  `Vid_ID` VARCHAR(45) GENERATED ALWAYS AS () VIRTUAL,
  `Vid_RES` VARCHAR(45) NULL,
  PRIMARY KEY (`Vid_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Video Sequence Start End`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Video Sequence Start End` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Video Sequence Start End` (
  `Vid_ID` VARCHAR(45) GENERATED ALWAYS AS () VIRTUAL,
  `Start_SEQ` VARCHAR(45) NULL,
  `End_SEQ` VARCHAR(45) NULL,
  PRIMARY KEY (`Vid_ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Video Subject and Tag`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Video Subject and Tag` (`Vid_ID`, `Action_Object`, `Tag_ID`) VALUES ('D100', 'Action_Object', 'Running_Dog');
INSERT INTO `mydb`.`Video Subject and Tag` (`Vid_ID`, `Action_Object`, `Tag_ID`) VALUES ('T252', 'Object', 'Tree');
INSERT INTO `mydb`.`Video Subject and Tag` (`Vid_ID`, `Action_Object`, `Tag_ID`) VALUES ('H189', 'Action_Object', 'Waving_Human');
INSERT INTO `mydb`.`Video Subject and Tag` (`Vid_ID`, `Action_Object`, `Tag_ID`) VALUES ('D851', 'Action_Object', 'Jumping_Dog');
INSERT INTO `mydb`.`Video Subject and Tag` (`Vid_ID`, `Action_Object`, `Tag_ID`) VALUES ('W744', 'Object', 'Water');
INSERT INTO `mydb`.`Video Subject and Tag` (`Vid_ID`, `Action_Object`, `Tag_ID`) VALUES ('C363', 'Action_Object', 'Running_Car');
INSERT INTO `mydb`.`Video Subject and Tag` (`Vid_ID`, `Action_Object`, `Tag_ID`) VALUES ('C479', 'Object', 'Car');
INSERT INTO `mydb`.`Video Subject and Tag` (`Vid_ID`, `Action_Object`, `Tag_ID`) VALUES ('H908', 'Action_Object', 'Jumping_Human');
INSERT INTO `mydb`.`Video Subject and Tag` (`Vid_ID`, `Action_Object`, `Tag_ID`) VALUES ('H229', 'Action_Object', 'Standing_Human');
INSERT INTO `mydb`.`Video Subject and Tag` (`Vid_ID`, `Action_Object`, `Tag_ID`) VALUES ('W467', 'Object', 'Water');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Frame Rerence`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Frame Rerence` (`Vid_ID`, `Frame_CL`) VALUES ('D100', 'Max');
INSERT INTO `mydb`.`Frame Rerence` (`Vid_ID`, `Frame_CL`) VALUES ('T252', 'Max');
INSERT INTO `mydb`.`Frame Rerence` (`Vid_ID`, `Frame_CL`) VALUES ('H189', 'Med');
INSERT INTO `mydb`.`Frame Rerence` (`Vid_ID`, `Frame_CL`) VALUES ('D851', 'Max');
INSERT INTO `mydb`.`Frame Rerence` (`Vid_ID`, `Frame_CL`) VALUES ('W744', 'Max');
INSERT INTO `mydb`.`Frame Rerence` (`Vid_ID`, `Frame_CL`) VALUES ('C363', 'Med');
INSERT INTO `mydb`.`Frame Rerence` (`Vid_ID`, `Frame_CL`) VALUES ('C479', 'Max');
INSERT INTO `mydb`.`Frame Rerence` (`Vid_ID`, `Frame_CL`) VALUES ('H908', 'Max');
INSERT INTO `mydb`.`Frame Rerence` (`Vid_ID`, `Frame_CL`) VALUES ('H229', 'Max');
INSERT INTO `mydb`.`Frame Rerence` (`Vid_ID`, `Frame_CL`) VALUES ('W467', 'Med');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Video Resolution`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Video Resolution` (`Vid_ID`, `Vid_RES`) VALUES ('D100', '360');
INSERT INTO `mydb`.`Video Resolution` (`Vid_ID`, `Vid_RES`) VALUES ('T252', '480');
INSERT INTO `mydb`.`Video Resolution` (`Vid_ID`, `Vid_RES`) VALUES ('H189', '360');
INSERT INTO `mydb`.`Video Resolution` (`Vid_ID`, `Vid_RES`) VALUES ('D851', '1080');
INSERT INTO `mydb`.`Video Resolution` (`Vid_ID`, `Vid_RES`) VALUES ('W744', '1080');
INSERT INTO `mydb`.`Video Resolution` (`Vid_ID`, `Vid_RES`) VALUES ('C363', '480');
INSERT INTO `mydb`.`Video Resolution` (`Vid_ID`, `Vid_RES`) VALUES ('C479', '480');
INSERT INTO `mydb`.`Video Resolution` (`Vid_ID`, `Vid_RES`) VALUES ('H908', '1080');
INSERT INTO `mydb`.`Video Resolution` (`Vid_ID`, `Vid_RES`) VALUES ('H229', '720');
INSERT INTO `mydb`.`Video Resolution` (`Vid_ID`, `Vid_RES`) VALUES ('W467', '720');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Video Sequence Start End`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Video Sequence Start End` (`Vid_ID`, `Start_SEQ`, `End_SEQ`) VALUES ('D100', '20s', '30s');
INSERT INTO `mydb`.`Video Sequence Start End` (`Vid_ID`, `Start_SEQ`, `End_SEQ`) VALUES ('T252', '12s', '24s');
INSERT INTO `mydb`.`Video Sequence Start End` (`Vid_ID`, `Start_SEQ`, `End_SEQ`) VALUES ('H189', '38s', '45s');
INSERT INTO `mydb`.`Video Sequence Start End` (`Vid_ID`, `Start_SEQ`, `End_SEQ`) VALUES ('D851', '15s', '52s');
INSERT INTO `mydb`.`Video Sequence Start End` (`Vid_ID`, `Start_SEQ`, `End_SEQ`) VALUES ('W744', '9s', '49s');
INSERT INTO `mydb`.`Video Sequence Start End` (`Vid_ID`, `Start_SEQ`, `End_SEQ`) VALUES ('C363', '22s', '30s');
INSERT INTO `mydb`.`Video Sequence Start End` (`Vid_ID`, `Start_SEQ`, `End_SEQ`) VALUES ('C479', '18s', '23s');
INSERT INTO `mydb`.`Video Sequence Start End` (`Vid_ID`, `Start_SEQ`, `End_SEQ`) VALUES ('H908', '27s', '37s');
INSERT INTO `mydb`.`Video Sequence Start End` (`Vid_ID`, `Start_SEQ`, `End_SEQ`) VALUES ('H229', '5s', '19s');
INSERT INTO `mydb`.`Video Sequence Start End` (`Vid_ID`, `Start_SEQ`, `End_SEQ`) VALUES ('W467', '42s', '59s');

COMMIT;

