-- MySQL Script generated by MySQL Workbench
-- Sun Mar 25 20:12:43 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;


SELECT `Vid_ID`, `Action_Object`, `Tag_ID` FROM `Video Subject and Tag` 

SELECT `Vid_ID`, `Frame_CL` FROM `Frame Rerence` 

SELECT `Vid_ID`, `Vid_RES` FROM `Video Resolution` 

SELECT `Vid_ID`, `Start_SEQ`, `End_SEQ` FROM `Video Sequence Start End` 




SELECT `Vid_ID`, `Frame_CL` FROM `Frame Rerence`
	WHERE column_name = `Frame_CL` 

SELECT `Vid_ID`, `Vid_RES` FROM `Video Resolution`
	WHERE  row_number() = 3 


JOIN `Vid_RES` ON `Video Resolution` AND `Frame_CL` ON `Frame Rerence` 

JOIN `Action_Object` ON `Video Subject and Tag` AND `Start_SEQ` ON `Video Sequence Start End` ;


